### ISSUE TITLE
Text doesnt look central due to margin left %

### ISSUE THREAD

**Issue by Jetski5822** [alfmoh/mysite#1]
Id ditch...

#projects {
    margin-left: 2%
}

#other {
    margin-left: 2%
}

#contacts {
    margin-left: 2%
}

#skills {
    margin-left: 2%
}

#myself {
    margin-left: 3%
}
#pic{
    margin-left: 3.08%
}
.otherInt {
    margin-left: 3%
}
.mail {
    margin-left: 1.5%;
}

**Comment by alfmoh** [comment]
Corrected. Thanks . :blush:
