### ISSUE TITLE
Add Location

### ISSUE THREAD

**Issue by Jetski5822** [alfmoh/mysite#2]
Where you based bro!

**Comment by alfmoh** [comment]
I'm in Russia at the moment. Saw your comment on my github. You are right.
Will check out. :) . Anyway, why are asking and where are you also based?

**Comment by Jetski5822** [comment]
I am in London, and saw you on Twitter... thought id let you know. Enjoy Russia!

**Comment by alfmoh** [comment]
That's great. Checked out your github. You are doing great. Thumbs up.
Got/Know any job position available?
